### ISSUE TITLE
搭建完显示网关错误[BUG]

### ISSUE THREAD

**Issue by page-55187** [FunnyWolf/Viper#141]
**描述Bug**
请简短描述遇到的Bug.

**如何复现**
请说明如何复现Bug:
1. 安装Viper
2. 打开浏览器
3. 输入密码
4. Bug出现了

**截图**
请提供Bug出现时的截图.

@Funnywolf

**Comment by page-55187** [comment]
Websocket 鉴权失败
内置模块加载完成,加载100个模块
自定义模块加载完成,加载0个模块
后台服务启动成功
Internal Server Error: /api/v1/core/baseauth/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
AssertionError: 'BaseAuthView' should either include a `queryset` attribute, or override the `get_queryset()` method.

**Comment by FunnyWolf** [comment]
进程初始化错误,重启docker容器即可 docker compose stop docker compose start
