### ISSUE TITLE
[BUG] thin的pid文件未清除导致重启msf后台服务无法启动

### ISSUE THREAD

**Issue by FunnyWolf** [FunnyWolf/Viper#145]
**复现步骤**
1. kill msf后台进程
2. 重启msf后台进程

**截图**
请提供Bug出现时的截图.
```
/root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/daemonizing.rb:190:in `remove_stale_pid_file': tmp/pids/thin.pid already exists, seems like it's already running (process ID: 133). Stop the process or delete tmp/pids/thin.pid. (Thin::PidFileExist)
	from /root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/daemonizing.rb:49:in `daemonize'
	from /root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/controllers/controller.rb:62:in `start'
	from /root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/runner.rb:203:in `run_command'
	from /root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/runner.rb:159:in `run!'
	from /root/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/thin-1.8.2/bin/thin:6:in `<top (required)>'
	from /root/.rbenv/versions/3.0.5/bin/thin:25:in `load'
	from /root/.rbenv/versions/3.0.5/bin/thin:25:in `<main>'
```
@Funnywolf

**Comment by FunnyWolf** [comment]
we should delete this file   /root/metasploit-framework/tmp/pids/thin.pid
