### ISSUE TITLE
[BUG] session加载报错

### ISSUE THREAD

**Issue by FunnyWolf** [FunnyWolf/Viper#157]
**复现步骤**
1. 开启任意监听
08/16/2023 01:44:38] [e(0)] meterpreter: Error running command load: NoMethodError private method `print' called for nil:NilClass
[08/16/2023 01:44:38] [d(0)] meterpreter: Call stack:
/root/metasploit-framework/lib/rex/ui/text/shell.rb:283:in `print'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:123:in `print'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1331:in `block in cmd_load'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `each'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `cmd_load'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/root/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:173:in `bootstrap'
/root/metasploit-framework/lib/msf/core/handler.rb:271:in `register_session'
/root/metasploit-framework/lib/msf/core/handler.rb:251:in `block in create_session'
/root/metasploit-framework/lib/msf/core/session_manager.rb:160:in `block (2 levels) in initialize_scheduler_threads'
/root/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[08/16/2023 01:44:38] [e(0)] core: NoMethodError private method `print' called for nil:NilClass
Call stack:
/root/metasploit-framework/lib/rex/ui/text/shell.rb:283:in `print'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:123:in `print'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1331:in `block in cmd_load'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `each'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `cmd_load'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/root/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:173:in `bootstrap'
/root/metasploit-framework/lib/msf/core/handler.rb:271:in `register_session'
/root/metasploit-framework/lib/msf/core/handler.rb:251:in `block in create_session'
/root/metasploit-framework/lib/msf/core/session_manager.rb:160:in `block (2 levels) in initialize_scheduler_threads'
/root/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'

**截图**
请提供Bug出现时的截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
未正确初始化的session的正常逻辑,不处理
