### ISSUE TITLE
[BUG] session加载powershell报错

### ISSUE THREAD

**Issue by FunnyWolf** [FunnyWolf/Viper#159]
**复现步骤**

[08/18/2023 11:23:32] [d(0)] core: pub_heartbeat_data num: 1
[08/18/2023 11:23:33] [d(0)] core: pub_heartbeat_data num: 1
[08/18/2023 11:23:33] [e(0)] meterpreter: Failed to load extension: The core_loadlib request failed with result: 2147942411.
[08/18/2023 11:23:33] [d(0)] meterpreter: Call stack:
/root/metasploit-framework/lib/rex/post/meterpreter/client_core.rb:385:in `use'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1335:in `block in cmd_load'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `each'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `cmd_load'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/root/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:432:in `load_powershell'
/root/metasploit-framework/modules/post/windows/manage/powershell/exec_powershell_mem.rb:72:in `run'
/root/metasploit-framework/lib/msf/base/simple/post.rb:152:in `job_run_proc'
/root/metasploit-framework/lib/msf/base/simple/post.rb:115:in `block in run_rpc'
/root/metasploit-framework/lib/rex/job.rb:49:in `block in start'
/root/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/root/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[08/18/2023 11:23:33] [e(0)] core: Rex::RuntimeError The core_loadlib request failed with result: 2147942411.
Call stack:
/root/metasploit-framework/lib/rex/post/meterpreter/client_core.rb:385:in `use'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1335:in `block in cmd_load'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `each'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1305:in `cmd_load'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/root/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/root/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:432:in `load_powershell'
/root/metasploit-framework/modules/post/windows/manage/powershell/exec_powershell_mem.rb:72:in `run'
/root/metasploit-framework/lib/msf/base/simple/post.rb:152:in `job_run_proc'
/root/metasploit-framework/lib/msf/base/simple/post.rb:115:in `block in run_rpc'
/root/metasploit-framework/lib/rex/job.rb:49:in `block in start'
/root/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/root/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[08/18/2023 11:23:34] [d(0)] core: pub_heartbeat_data num: 1
[08/18/2023 11:23:34] [d(0)] core: pub_heartbeat_data num: 1

**截图**
Bug截图.

@Funnywolf

**Comment by FunnyWolf** [comment]
https://github.com/rapid7/metasploit-framework/issues/16784
